### ISSUE TITLE
How do you enforce non-contract calls?

### ISSUE THREAD

**Issue by SCBuergel** [curvefi/curve-dao-contracts#22]
Your docs state that

> The account which locks the tokens cannot be a smart contract (because can be tradable and/or tokenized), unless it is one of whitelisted smart contracts (for example, widely used multi-signature wallets).

How do you want to enforce that though in a way that cannot be cheated by technical means (e.g. constructor calls)?

**Comment by iamdefinitelyahuman** [comment]
The current logic around restricting contracts is found here:

https://github.com/curvefi/curve-dao-contracts/blob/25a0c25e4e77ff493b977fb95a3cddd42df735e3/contracts/VotingEscrow.vy#L171-L182

`smart_wallet_checker` will compare the hash of the code at `addr` against a mapping of approved hashes, and revert if the contract is not approved.  Use of `CREATE2`/`SELFDESTRUCT` to make all interactions via constructor will still trigger this logic due to `addr != tx.origin` and ultimately revert because `0x00` won't be an approved hash.

**Comment by SCBuergel** [comment]
[`tx.origin` might not return meaningful values past Serenity](https://ethereum.stackexchange.com/questions/196/how-do-i-make-my-dapp-serenity-proof). Depending on the timeline of your project and Serenity that might be an issue or not.

**Comment by iamdefinitelyahuman** [comment]
:+1: thanks for mentioning this - we've looked at it some more and ultimately decided that it's still the approach we want to take.

Closing this issue for now, if you want to continue discussion feel free to join us on [Telegram](https://t.me/curvefi) or [Discord](https://discord.gg/rgrfS7W).
